export const productProps = {
  id: String,
  num: Number,
  title: String,
  city: String,
  address: String,
  category: String,
  unit: String,
  evaluate: Number,
  evaluateNum: Number,
  collectStatus: Boolean,
  price: Number,
  origin_price: Number,
  date: Number,
  coordinates: Object,
  description: String,
  is_enabled: Boolean,
  imageUrl: String,
  imagesUrl: Array,
  features: String,
  content: String,
};
